version: '2.1'
services:
    db:
        build: ./db
        command: --max_connections=400
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        ports:
            - "3306:3306"
        healthcheck:
            test: "exit 0"
    
    ebay_gallery:
        build: .
        depends_on:
            db:
                condition: service_healthy
        command: sh -c './wait-for-it db:3306 -t 30 -- npm run seedDocker; npm start'
        links:
            - db:db
        environment:
            - MYSQL_HOST=db
            - ENVIRONMENT=production
        ports:
            - "3003:3003"
